# Generated by Django 5.0.4 on 2024-05-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
